volumes:
  database:
    driver: local

services:
  postgres-turbostarter:
    image: postgres:14.13-alpine
    ports:
      - 5888:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turbostarter
      POSTGRES_USER: turbostarter
